# Colors:
#   BLACK = &0, DARK_BLUE = &1, DARK_GREEN = &2, DARK_AQUA = &3
#   DARK_RED = &4, DARK_PURPLE = &5, GOLD = &6, GRAY = &7
#   DARK_GRAY = &8, BLUE = &9, GREEN = &a, AQUA = &b
#   RED = &c, LIGHT_PURPLE = &d, YELLOW = &e, WHITE = &f

# Formats:
#   OBFUSCATED = &k, BOLD = &l, STRIKETHROUGH = &m,
#   UNDERLINE = &n, ITALIC = &o, RESET = &r

messages:
  help:
    - "&e--------- &rHelp: QuickShulker &e---------------------------&r"
    - "&7Below is a list of all QuickShulker commands:&r"
    - "&6/quickshulker reload: &rReload this plugin"
  no-permission: "&cYou don't have permission to do this!"
  plugin-reloading: "&cReloading plugin..."
  plugin-reloaded: "&aPlugin reloaded!"

settings:
  # 0 for left click, 1 for right click
  interact-button: 1
  # need sneak for opening shulker
  need-sneak: false